title: Melina Berredo # your name (or website title) here
logo: "https://raw.githubusercontent.com/mberredo/mberredo.github.io/master/headshot.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome To My Portfolio!
  <br><br>
  Data Aficionado | Generating Insights | Traveler  
  <a href="https://www.linkedin.com/in/melinaberredo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
